steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://ecosentinel-backend-728645350771.asia-south1.run.app/api/v1'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyC18GMdmeghZB2b6pdgif0igwWyT6CEaZY'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=ecosentinel-31c16.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=ecosentinel-31c16'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=ecosentinel-31c16.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=104114015666'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:104114015666:web:279da9275020bcc29f28ab'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-44KTMMNPZS'
      - '-t'
      - '$_IMAGE_NAME'
      - '.'
images:
  - '$_IMAGE_NAME'
