steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://ecosentinel-backend-xxxxxx.a.run.app/api/v1'
      - '-t'
      - '$_IMAGE_NAME'
      - '.'
images:
  - '$_IMAGE_NAME'
